# .github/workflows/load-test.yml
# file

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run local k6 test
        run: k6 run ./sp_api_performance/tests/multipleScenarios.js -e environment=preprod --summary-export=summary-report.js

      - name: Deploy report to Github Pages
        if: always()s
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report